# Generated by Django 3.1.4 on 2021-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('storageType', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=200)),
                ('storageCapacity', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('graphics', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('ssdExpansion', models.CharField(max_length=200)),
            ],
        ),
    ]
