# Generated by Django 3.1.4 on 2021-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ssdExpansion',
            field=models.CharField(choices=[('available', True), ('not available', False)], default=True, max_length=200),
        ),
    ]
